plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'tgb.cryptoexchange'
version = '0.1-SNAPSHOT'
description = 'support-users'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-kafka'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.0'

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'com.mysql:mysql-connector-j'

    implementation 'org.springframework.kafka:spring-kafka'

    implementation 'commons-codec:commons-codec:1.18.0'
    implementation 'org.springframework.security:spring-security-crypto'

    implementation 'io.micrometer:micrometer-registry-prometheus'

    implementation 'org.semver4j:semver4j:6.0.0'
    implementation 'tgb.cryptoexchange:common-api:1.1.0'
    implementation 'tgb.cryptoexchange:commons:1.0'

    implementation 'io.jsonwebtoken:jjwt:0.13.0'

    implementation 'com.fasterxml.uuid:java-uuid-generator:5.2.0'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    compileOnly 'jakarta.annotation:jakarta.annotation-api:3.0.0'


    testImplementation "org.springframework.boot:spring-boot-starter-flyway"
    testImplementation "org.flywaydb:flyway-mysql"
    testImplementation "org.springframework.boot:spring-boot-starter-test"
    testImplementation "org.springframework.boot:spring-boot-starter-data-jpa-test"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testImplementation "org.testcontainers:junit-jupiter:1.21.4"
    testImplementation "org.testcontainers:kafka:1.21.4"
    testImplementation "org.testcontainers:mysql:1.21.4"
    testImplementation "org.assertj:assertj-core:3.27.7"
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

test {
    systemProperty "file.encoding", "UTF-8"
}

tasks.jar {
    archiveFileName = "support-users.jar"
}

bootJar {
    archiveFileName = 'support-users.jar'
}